### ISSUE TITLE
get_dict_for_symbol() does not work if symbol name starts with "^"

### ISSUE THREAD

**Issue by helpme1** [F2011B/ami2py#3]
I notice that get_dict_for_symbol() does not work for symbols that start with "^" and "~'. An example would be the yahoo symbol for S&P 500 "^GSPC". 

This will be a problem for most yahoo stock indices.

Thanks for your work. It is useful for Amibroker users.

**Comment by F2011B** [comment]
I implemented the fix. However, the automatic build chain is currently broken.
Therefore, no new version was deployed on pypi.
Please use the git repo and try it. 
Would be nice if you can close the ticket if it works for you!

**Comment by helpme1** [comment]
> I implemented the fix. However, the automatic build chain is currently broken. Therefore, no new version was deployed on pypi. Please use the git repo and try it. Would be nice if you can close the ticket if it works for you!

Thank you for the quick action. I have verified that the fix works. I will close the ticket.
